### ISSUE TITLE
Before after operator hook 

### ISSUE THREAD

**Issue by robcxyz** [insight-infrastructure/nukikata#9]
Would be nice to have a keyword in the operator that can trigger a hook.  This would sort of be like a handler in Ansible but should be able to potentially return a value.  

Something like. 

```yaml
stuff: things 
an_operator:
  type: nukikata
  template: fake-repo-tmpl-nuki
  no_input: true
  before_hook: path/to/script.py
  after_hook: path/to/script.sh 
```

Could be used in many contexts.
